apiVersion: v1
kind: Configmap
metadata:
   name: backend
   namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: expense
  labels: 
    app : backend
    tier: api
    project: expense
spec:
  replicas: 1
  selector:
   matchLabels:
     app: backend
     tier: api
     project: expense
  template:
     metadata:
       labels: 
          app: backend
          tier: api
          project: expense
     spec: 
      containers: 
        - name: backend
          image: thanug828189/backend:v1 
          envFrom:
            - configMapRef: 
                  name: backend

---
kind: Service
apiVersion: v1
metadata: 
    name: backend
    namespace: expense
spec:
  selector:        
    app: expense
    tier: api
    project: expense
  ports: 
   - name: backend-port
     protocl: TCP
     port: 8080
     targetPort: 8080
